=== Zalaaan0/E3K8G9WebXML/E3K8G9/E3K8G9_kurzusfelvetel.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT kurzusfelvetel (hallgato, kurzusok)>

<!ATTLIST kurzusfelvetel
        tanev CDATA #REQUIRED
        egyetem CDATA #FIXED "ME">

<!ELEMENT hallgato (hnev, szulev, szak+)>
<!ATTLIST hallgato id ID #REQUIRED>

<!ELEMENT hnev (#PCDATA)>
<!ELEMENT szulev (#PCDATA)>
<!ELEMENT szak (#PCDATA)>
<!ATTLIST szak evf CDATA #REQUIRED>

<!ELEMENT kurzusok (kurzus*)>

<!ELEMENT kurzus (kurzusnev, kredit, hely, idopont?, (oktato, oraado)+ )>
<!ATTLIST kurzus
        id ID #REQUIRED
        jovahagyas (igen | nem) "nem"
        nyelv CDATA #IMPLIED>

<!ELEMENT kurzusnev (#PCDATA)>
<!ELEMENT kredit (#PCDATA)>
<!ELEMENT hely (#PCDATA)>
<!ELEMENT idopont (#PCDATA)>
<!ELEMENT oktato (#PCDATA)>

=== Zalaaan0/E3K8G9WebXML/E3K8G9/E3K8G9_kurzusfelvetel.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE kurzusfelvetel SYSTEM "E3K8G9_kurzusfelvetel.dtd">

<kurzusfelvetel tanev="2026_2027 I." egyetem="ME">
    <hallgato>
        <hnev>Kriston Zalán</hnev>
        <szulev>2004</szulev>
        <szak evf="3">Mérnökinformatikus</szak>
    </hallgato>

    <kurzusok>
        <kurzus id="k01">
            <kurzusnev>Webes adatkezelő környezetek</kurzusnev>
            <kredit>5</kredit>
            <hely>Inf/101</hely>
            <idopont>Szerda 12:00-13:30</idopont>
            <oktato>Dr. Bednarik László</oktato>
        </kurzus>
        <kurzus id="k02">
            <kurzusnev>Web technológiák</kurzusnev>
            <kredit>5</kredit>
            <hely>Inf/101</hely>
            <idopont>Hétfő 14:00-15:30</idopont>
            <oktato>Dr. Agárdi Anita</oktato>
        </kurzus>
    </kurzusok>
</kurzusfelvetel>
